### PR TITLE
Added CORS

### PR DESCRIPTION
**Pull request by Vemka**
check if everything works properly - my simple ajax tests showed that it works, but somehow ignores origins settings - for me ip whitelist didnt work

### CODE REVIEW

**Review by ifrins — COMMENTED** [review]
We need to make sure it adds the ```Access-Control-Allow-Credentials``` header to true so we can pass tokens via the ```Authorization``` header. Can you check it?

**Comment by Vemka** [comment]
Ok, Access-Control-Allow-Credentials header is added, this is my browser header screen:
https://i.imgur.com/BI6OFo2.png
one thing i dont understand - I connect using 192.168.1.103 ip (on screen below), but Access control  allow origin header is still 127.0.0.1....

**Comment by 3nr1c** [comment]
If I'm not wrong, the Host header (192.168.1.103:5000) is _sent_ on each request, and doesn't tell anything about the requester. So this would be correct behaviour, because your IP as a local requester is indeed 127.0.0.1 (=== localhost)

**Comment by Vemka** [comment]
good. then we need some real requests to api to test that it works as intended

**Comment by ifrins** [comment]
Browsers do a CORS preflight request using the `OPTIONS` HTTP verb. There it negotiates if the browser is able to make a request (normally using some fields such as the `Access-Control-Allow-Origin` – not the `Host` header.). This [MDN link](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) has a nice and easy-to-understand CORS overview too.

You can try CORS with this website https://www.test-cors.org/

**Comment by 3nr1c** [comment]
lpgtm

**Pull request merged**
